### ISSUE TITLE
cloud environment: fsspec to master?

### ISSUE THREAD

**Issue by matt-long** [cmip6hack/project-template#6]
We were having trouble reading zarr stores on Google:
    https://github.com/intake/filesystem_spec/issues/157

Does fsspec/master solve the problem?

**Comment by andersy005** [comment]
> Does fsspec/master solve the problem?

I just tested the notebook with fsspec and gcsfs master branches, and everything seems to be working great

**Comment by rabernat** [comment]
So do we need to get a PR going on https://github.com/pangeo-data/pangeo-cloud-federation to update fsspec? Or has this already been done?
