### ISSUE TITLE
Move catalogs out of this template?

### ISSUE THREAD

**Issue by rabernat** [cmip6hack/project-template#7]
It might not be wise to have the catalog live in this repo. I propose we add them to https://github.com/pangeo-data/pangeo-datastore and then reference that from here.

**Comment by matt-long** [comment]
We currently have the collections living in https://github.com/NCAR/intake-esm-datastore and duplicated here for (1) purposes of reproducibility and (2) because Cheyenne batch nodes do not have Internet access—so users there will need a local copy.

**Comment by rabernat** [comment]
I see your point. But I'm worried that having a relative path in the notebook with _hinder_ rather than help reproducibility (also related to #8).

Could we do the following?
- pick a path on glade for the official catalog location and use an absolute path in cell 5 for the glade catalog
- reference https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json in cell 5 for the cloud catalog

**Comment by rabernat** [comment]
I'm willing to drop this if we can add some text and links to the `hello_world` notebooks that explain where to find the official versions of these catalogs ( https://raw.githubusercontent.com/NCAR/intake-esm-datastore).

**Comment by matt-long** [comment]
I am happy to make these changes. 

We have the catalogs on glade and could use this path:
/glade/collections/cmip/catalog/intake-esm-datastore/catalogs

but that's outside the project's direct control (of course the actual data is too), so it's possible to change files at that location without those changes being reflected in the project—and thus breaking reproducibility.

I was thinking about using `git subtree` to manage the catalogs subdirectory in the project. That doesn't solve the relative path issue, but would preserve the link to the primary source. Could be support by an `update_catalogs` script, for instance.  

What do you think?

**Comment by rabernat** [comment]
No to git subtree. Let's keep things as simple as possible.

**Comment by matt-long** [comment]
Yeah...that's why I haven't pursued it yet.
