### ISSUE TITLE
Remove utils.py?

### ISSUE THREAD

**Issue by rabernat** [cmip6hack/project-template#8]
Let's try to remove the utils module. The convenience we gain by having the hostname check (3 lines of code) in an external module is outweighed by the introduction of a dependency, which makes the notebooks less portable (won't work in sub-directories, etc.)

**Comment by matt-long** [comment]
I imagine teams extending utils.py with functionality required across the collection of notebooks developed for a project. It would be easy to put the hostname check directly in the notebook, sure, but there may be other such common code, so I wanted to provide a template.

**Comment by rabernat** [comment]
Ok I'm convinced. But can you put that in a module-level comment in `utils.py` and also a comment to this effect in the notebook?

**Comment by matt-long** [comment]
Sure, that would help make the intentions clear.
